# Generated by Django 5.1.6 on 2025-02-06 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Name"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Name"
                    ),
                ),
                (
                    "api_key",
                    models.CharField(max_length=255, verbose_name="API key"),
                ),
            ],
            options={
                "verbose_name": "Provider",
                "verbose_name_plural": "Provider",
            },
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "block_number",
                    models.BigIntegerField(verbose_name="Block number"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, verbose_name="Created at"
                    ),
                ),
                (
                    "stored_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Stored at"
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="blockchains.currency",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="blockchains.provider",
                    ),
                ),
            ],
            options={
                "unique_together": {("currency", "block_number")},
            },
        ),
    ]
