# Generated by Django 5.1.6 on 2025-02-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blockchains", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="block",
            options={"verbose_name": "Block", "verbose_name_plural": "Blocks"},
        ),
        migrations.AlterModelOptions(
            name="currency",
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
            },
        ),
        migrations.AlterModelOptions(
            name="provider",
            options={
                "verbose_name": "Provider",
                "verbose_name_plural": "Providers",
            },
        ),
        migrations.AlterField(
            model_name="provider",
            name="api_key",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="API key"
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="name",
            field=models.CharField(
                editable=False, max_length=50, unique=True, verbose_name="Name"
            ),
        ),
    ]
