# Generated by Django 5.1.6 on 2025-02-07 19:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "blockchains",
            "0002_alter_block_options_alter_currency_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="block",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Block",
                "verbose_name_plural": "Blocks",
            },
        ),
    ]
