# Generated by Django 5.1.6 on 2025-02-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blockchains", "0003_alter_block_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="api_key",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="API key",
            ),
        ),
    ]
